definitions:
  model.C2S_Register:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/AddSinglePersonAndMatch:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: 要註冊的帳號
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.C2S_Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      summary: 註冊帳號
      tags:
      - example
swagger: "2.0"
