definitions:
  model.C2S_Register:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.S2C_Login:
    properties:
      token:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  response.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/AddSinglePersonAndMatch:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: 要註冊的帳號
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.C2S_Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.S2C_Login'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: 註冊帳號
      tags:
      - example
swagger: "2.0"
